import React, { useState } from 'react';
import { Search, RefreshCw, ArrowUpRight, ArrowDownRight, Check, ChevronRight, Share2, Copy, Columns3, ListFilter } from 'lucide-react';
import { Currency } from '../types/currency';
import { useTheme } from '../context/ThemeContext';
import { CurrencyComparisonWidget } from './CurrencyComparisonWidget';

interface Props {
  currencies: Currency[];
  lastUpdated: string;
  isOnlineSource: boolean;
  onRefreshRates: () => Promise<void>;
  isRefreshing: boolean;
  onSelectForConvert: (curr: Currency) => void;
  soundEnabled: boolean;
  onPlayClick: () => void;
}

export const RatesTab: React.FC<Props> = ({
  currencies,
  lastUpdated,
  isOnlineSource,
  onRefreshRates,
  isRefreshing,
  onSelectForConvert,
  onPlayClick,
}) => {
  const { theme } = useTheme();
  const [ratesMode, setRatesMode] = useState<'directory' | 'compare'>('directory');
  const [query, setQuery] = useState('');
  const [selectedFilter, setSelectedFilter] = useState<string>('all');
  const [viewMode, setViewMode] = useState<'to_mad' | 'from_100_mad'>('to_mad');
  const [shareFeedback, setShareFeedback] = useState<string | null>(null);

  const filterTabs = [
    { id: 'all', label: 'All Currencies' },
    { id: 'major', label: 'Top 6' },
    { id: 'europe', label: 'Europe' },
    { id: 'gulf', label: 'Gulf (الخليج)' },
    { id: 'americas', label: 'Americas' },
    { id: 'africa', label: 'Africa & Asia' },
  ];

  const filteredCurrencies = currencies.filter((c) => {
    const matchesQuery =
      c.code.toLowerCase().includes(query.toLowerCase()) ||
      c.name.toLowerCase().includes(query.toLowerCase()) ||
      c.country.toLowerCase().includes(query.toLowerCase()) ||
      c.nameAr.includes(query);

    const matchesFilter =
      selectedFilter === 'all' ||
      c.category === selectedFilter ||
      (selectedFilter === 'major' && ['EUR', 'USD', 'GBP', 'SAR', 'AED', 'CAD'].includes(c.code)) ||
      (selectedFilter === 'africa' && (c.category === 'africa' || c.category === 'asia_pacific'));

    return matchesQuery && matchesFilter;
  });

  const formattedDate = new Date(lastUpdated).toLocaleDateString([], {
    month: 'short',
    day: 'numeric',
    hour: '2-digit',
    minute: '2-digit',
  });

  const generateRatesSummary = (): string => {
    const dateStr = new Date(lastUpdated).toLocaleDateString([], {
      month: 'short',
      day: 'numeric',
      year: 'numeric',
      hour: '2-digit',
      minute: '2-digit',
    });

    // Select either the filtered list (if user filtered) or the top benchmark currencies
    const targetList =
      filteredCurrencies.length > 0 && filteredCurrencies.length <= 10
        ? filteredCurrencies
        : currencies.filter((c) =>
            ['EUR', 'USD', 'GBP', 'SAR', 'AED', 'CAD', 'CHF', 'QAR', 'KWD', 'TRY'].includes(c.code)
          );

    const lines: string[] = [
      `🇲🇦 Moroccan Dirham (MAD) Exchange Rates`,
      `📅 Ref: ${dateStr} (${isOnlineSource ? 'Bank Al-Maghrib Live' : 'Cached Benchmark'})`,
      ``,
    ];

    targetList.forEach((c) => {
      const toMad = c.rateToMad.toFixed(c.rateToMad < 1 ? 4 : 3);
      const fromMad = (100 / (c.rateToMad || 1)).toFixed(2);
      lines.push(`${c.flag} 1 ${c.code} = ${toMad} MAD  |  100 MAD = ${fromMad} ${c.code}`);
    });

    lines.push(``);
    lines.push(`Generated by DirhamPay - Moroccan Dirham Converter`);
    return lines.join('\n');
  };

  const handleShareRates = async () => {
    onPlayClick();
    const summary = generateRatesSummary();

    if (typeof navigator !== 'undefined' && navigator.share) {
      try {
        await navigator.share({
          title: 'Moroccan Dirham (MAD) Exchange Rates',
          text: summary,
        });
        setShareFeedback('Shared successfully!');
        setTimeout(() => setShareFeedback(null), 2500);
        return;
      } catch (err: unknown) {
        if (err instanceof Error && err.name === 'AbortError') {
          return;
        }
      }
    }

    // Fallback to clipboard
    try {
      if (typeof navigator !== 'undefined' && navigator.clipboard) {
        await navigator.clipboard.writeText(summary);
        setShareFeedback('Rates copied to clipboard!');
      } else {
        setShareFeedback('Copied!');
      }
    } catch {
      setShareFeedback('Failed to copy');
    }
    setTimeout(() => setShareFeedback(null), 2500);
  };

  // Simple SVG Sparkline renderer
  const renderSparkline = (points: number[], isPositive: boolean) => {
    if (!points || points.length < 2) return null;
    const min = Math.min(...points);
    const max = Math.max(...points);
    const range = max - min || 1;
    const width = 56;
    const height = 20;

    const pathD = points
      .map((val, idx) => {
        const x = (idx / (points.length - 1)) * width;
        const y = height - ((val - min) / range) * (height - 4) - 2;
        return `${idx === 0 ? 'M' : 'L'} ${x.toFixed(1)} ${y.toFixed(1)}`;
      })
      .join(' ');

    return (
      <svg width={width} height={height} className="overflow-visible">
        <path
          d={pathD}
          fill="none"
          stroke={isPositive ? '#10b981' : '#f43f5e'}
          strokeWidth="1.75"
          strokeLinecap="round"
          strokeLinejoin="round"
        />
      </svg>
    );
  };

  return (
    <div className="flex flex-col flex-1 pb-4 relative">
      {/* Toast Notification for Share / Copy */}
      {shareFeedback && (
        <div className="absolute top-2 left-4 right-4 z-40 bg-emerald-600 text-white text-xs font-semibold px-3 py-2 rounded-xl shadow-lg border border-emerald-400/40 flex items-center justify-between animate-in fade-in slide-in-from-top-2 duration-200">
          <div className="flex items-center gap-1.5">
            <Check className="w-4 h-4 text-emerald-200" />
            <span>{shareFeedback}</span>
          </div>
          <span className="text-[10px] text-emerald-200">Ready to paste</span>
        </div>
      )}

      {/* Header Info */}
      <div className="px-4 pt-3 pb-2 border-b border-slate-800/80">
        <div className="flex items-center justify-between">
          <div>
            <h2 className="text-base font-bold text-white tracking-tight flex items-center gap-1.5">
              <span>Bank Al-Maghrib Rates</span>
              <span className={`text-[10px] px-1.5 py-0.5 rounded ${theme.badgeBg} font-mono`}>
                BAM Benchmark
              </span>
            </h2>
            <p className="text-[11px] text-slate-400 mt-0.5">
              Ref: {formattedDate} {isOnlineSource ? '(Live Central Sync)' : '(Offline Cached)'}
            </p>
          </div>

          {/* Action Buttons: Share & Sync */}
          <div className="flex items-center gap-1.5">
            <button
              onClick={handleShareRates}
              className={`flex items-center gap-1 px-2.5 py-1.5 rounded-xl ${theme.accentBgLight} ${theme.accentText} text-xs font-semibold border ${theme.accentBorder} transition active:scale-95 shadow-sm`}
              title="Share or copy current rates summary"
              aria-label="Share exchange rates summary"
            >
              {shareFeedback ? (
                <Check className={`w-3.5 h-3.5 ${theme.accentText}`} />
              ) : (
                <Share2 className="w-3.5 h-3.5" />
              )}
              <span>{shareFeedback ? 'Copied' : 'Share'}</span>
            </button>

            <button
              onClick={() => {
                onPlayClick();
                onRefreshRates();
              }}
              disabled={isRefreshing}
              className="flex items-center gap-1 px-2.5 py-1.5 rounded-xl bg-slate-800 hover:bg-slate-700 text-slate-200 text-xs font-medium border border-slate-700/60 transition disabled:opacity-50 active:scale-95"
              title="Refresh exchange rates"
              aria-label="Sync rates with central bank"
            >
              <RefreshCw className={`w-3.5 h-3.5 ${isRefreshing ? `animate-spin ${theme.accentText}` : ''}`} />
              <span>Sync</span>
            </button>
          </div>
        </div>

        {/* Mode Selector Pill Bar */}
        <div className="flex p-1 bg-slate-950/90 rounded-xl border border-slate-800/80 mt-2.5">
          <button
            onClick={() => {
              onPlayClick();
              setRatesMode('directory');
            }}
            className={`flex-1 py-1.5 text-xs font-semibold rounded-lg flex items-center justify-center gap-1.5 transition ${
              ratesMode === 'directory'
                ? `${theme.accentBg} text-white shadow-sm`
                : 'text-slate-400 hover:text-white'
            }`}
          >
            <ListFilter className="w-3.5 h-3.5" />
            <span>Rates Directory</span>
          </button>
          <button
            onClick={() => {
              onPlayClick();
              setRatesMode('compare');
            }}
            className={`flex-1 py-1.5 text-xs font-semibold rounded-lg flex items-center justify-center gap-1.5 transition ${
              ratesMode === 'compare'
                ? `${theme.accentBg} text-white shadow-sm`
                : 'text-slate-400 hover:text-white'
            }`}
          >
            <Columns3 className="w-3.5 h-3.5" />
            <span>Comparison (3-4)</span>
          </button>
        </div>

        {ratesMode === 'directory' && (
          <>
            {/* View Toggle Bar (1 Unit vs 100 MAD) */}
            <div className="flex p-1 bg-slate-950/80 rounded-xl border border-slate-800 mt-2.5">
              <button
                onClick={() => {
                  onPlayClick();
                  setViewMode('to_mad');
                }}
                className={`flex-1 py-1 text-xs font-semibold rounded-lg transition ${
                  viewMode === 'to_mad' ? `${theme.accentBg} text-white shadow-sm` : 'text-slate-400'
                }`}
              >
                1 Foreign = X MAD
              </button>
              <button
                onClick={() => {
                  onPlayClick();
                  setViewMode('from_100_mad');
                }}
                className={`flex-1 py-1 text-xs font-semibold rounded-lg transition ${
                  viewMode === 'from_100_mad' ? `${theme.accentBg} text-white shadow-sm` : 'text-slate-400'
                }`}
              >
                100 MAD = X Foreign
              </button>
            </div>

            {/* Search input */}
            <div className="relative mt-2.5">
              <Search className="absolute left-3 top-1/2 -translate-y-1/2 w-4 h-4 text-slate-400" />
              <input
                type="text"
                placeholder="Search code, country or Arabic name..."
                value={query}
                onChange={(e) => setQuery(e.target.value)}
                className={`w-full pl-9 pr-3 py-1.5 rounded-xl bg-slate-900 border border-slate-800 text-xs text-white placeholder-slate-400 focus:outline-none focus:ring-1 ${theme.accentRing}`}
              />
            </div>

            {/* Categories scroll */}
            <div className="flex items-center gap-1.5 overflow-x-auto py-2 no-scrollbar text-xs">
              {filterTabs.map((tab) => (
                <button
                  key={tab.id}
                  onClick={() => {
                    onPlayClick();
                    setSelectedFilter(tab.id);
                  }}
                  className={`px-3 py-1 rounded-lg text-xs font-medium whitespace-nowrap transition-colors ${
                    selectedFilter === tab.id
                      ? `${theme.accentBgLight} ${theme.accentText} border ${theme.accentBorder}`
                      : 'bg-slate-900/60 text-slate-400 border border-slate-800 hover:text-white'
                  }`}
                >
                  {tab.label}
                </button>
              ))}
            </div>
          </>
        )}
      </div>

      {ratesMode === 'compare' ? (
        <div className="flex-1 overflow-y-auto px-4 py-3">
          <CurrencyComparisonWidget
            currencies={currencies}
            onSelectForConvert={onSelectForConvert}
            onPlayClick={onPlayClick}
          />
        </div>
      ) : (
        /* Rates Table / List with Quick Comparison Entry Card */
        <div className="flex-1 overflow-y-auto px-4 divide-y divide-slate-800/60">
          <div className="pt-2.5 pb-1">
            <button
              onClick={() => {
                onPlayClick();
                setRatesMode('compare');
              }}
              className="w-full p-2.5 rounded-xl bg-gradient-to-r from-slate-900 to-slate-850 border border-slate-800 hover:border-emerald-500/40 text-left flex items-center justify-between transition group shadow-sm active:scale-98"
            >
              <div className="flex items-center gap-2.5">
                <div className={`p-1.5 rounded-lg ${theme.accentBgLight} ${theme.accentText}`}>
                  <Columns3 className="w-4 h-4" />
                </div>
                <div>
                  <div className="text-xs font-bold text-white group-hover:text-emerald-300 transition-colors flex items-center gap-1.5">
                    <span>Side-by-Side Comparison Table</span>
                    <span className="text-[10px] px-1.5 py-0.2 rounded bg-amber-500/20 text-amber-300 border border-amber-500/30 font-medium">3-4 Currencies</span>
                  </div>
                  <div className="text-[10px] text-slate-400">
                    Compare exchange rates, buy/sell spreads, and rapid price checks side-by-side
                  </div>
                </div>
              </div>
              <ChevronRight className="w-4 h-4 text-slate-500 group-hover:text-emerald-400 group-hover:translate-x-0.5 transition-all shrink-0" />
            </button>
          </div>
        {filteredCurrencies.map((curr) => {
          const isPositive = curr.change24h >= 0;
          const displayRate =
            viewMode === 'to_mad'
              ? `${curr.rateToMad.toFixed(curr.rateToMad < 1 ? 4 : 3)} MAD`
              : `${(100 / (curr.rateToMad || 1)).toFixed(2)} ${curr.code}`;

          const buyRate = (curr.rateToMad * (1 + curr.bankBuySpread)).toFixed(3);
          const sellRate = (curr.rateToMad * (1 + curr.bankSellSpread)).toFixed(3);

          return (
            <div
              key={curr.code}
              onClick={() => {
                onPlayClick();
                onSelectForConvert(curr);
              }}
              className="py-3 flex items-center justify-between hover:bg-slate-900/50 px-1 -mx-1 rounded-xl transition cursor-pointer group"
            >
              {/* Left: Flag & Details */}
              <div className="flex items-center gap-3">
                <span className="text-2xl select-none" role="img" aria-label={curr.country}>
                  {curr.flag}
                </span>
                <div>
                  <div className="flex items-center gap-1.5">
                    <span className="text-sm font-bold text-white tracking-tight">{curr.code}</span>
                    <span className="text-xs text-slate-400 font-mono">({curr.symbol})</span>
                    <span className="text-xs text-emerald-400 font-arabic">{curr.nameAr}</span>
                  </div>
                  <div className="text-[11px] text-slate-400 truncate max-w-[130px] sm:max-w-[180px]">
                    {curr.name} · {curr.country}
                  </div>
                  {/* Bank Buy / Sell Spread micro caption */}
                  <div className="text-[10px] text-slate-500 font-mono mt-0.5">
                    Buy: {buyRate} · Sell: {sellRate}
                  </div>
                </div>
              </div>

              {/* Middle: Sparkline Chart */}
              <div className="hidden sm:block px-2">
                {renderSparkline(curr.sparkline, isPositive)}
              </div>

              {/* Right: Rate & Trend & Convert trigger */}
              <div className="flex items-center gap-2">
                <div className="text-right">
                  <div className="text-sm font-bold text-white tabular-nums">{displayRate}</div>
                  <div
                    className={`text-[10px] font-semibold tabular-nums flex items-center justify-end gap-0.5 ${
                      isPositive ? 'text-emerald-400' : 'text-rose-400'
                    }`}
                  >
                    {isPositive ? (
                      <ArrowUpRight className="w-3 h-3" />
                    ) : (
                      <ArrowDownRight className="w-3 h-3" />
                    )}
                    <span>
                      {isPositive ? '+' : ''}
                      {curr.change24h}%
                    </span>
                  </div>
                </div>

                <div className="p-1 rounded-lg text-slate-500 group-hover:text-emerald-400 group-hover:bg-emerald-950/40 transition">
                  <ChevronRight className="w-4 h-4" />
                </div>
              </div>
            </div>
          );
        })}
        </div>
      )}
    </div>
  );
};

